version: '3.8'

networks:
  proxy-network:
    external: false

services:
  # Nginx reverse proxy with automatic virtual host detection
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: malris-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhosts:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy-network
    restart: unless-stopped

  # Let's Encrypt companion for automatic SSL certificates
  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: malris-acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=admin@kraig.io
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network
    restart: unless-stopped

  # Malris application
  app:
    image: registry.digitalocean.com/kraig-registry/malris:latest
    container_name: malris-app
    environment:
      - VIRTUAL_HOST=malris.kraig.io
      - LETSENCRYPT_HOST=malris.kraig.io
      - LETSENCRYPT_EMAIL=admin@kraig.io
      - NUXT_SUPABASE_URL=${NUXT_SUPABASE_URL}
      - NUXT_SUPABASE_ANON_KEY=${NUXT_SUPABASE_ANON_KEY}
      - NUXT_PUBLIC_SUPABASE_URL=${NUXT_PUBLIC_SUPABASE_URL}
      - NUXT_PUBLIC_SUPABASE_ANON_KEY=${NUXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - proxy-network
    restart: unless-stopped